# Generated by Django 3.1.3 on 2020-11-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surn', models.CharField(max_length=20)),
                ('pasw', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('file_info', models.FileField(upload_to='')),
            ],
        ),
    ]
