# Generated by Django 3.1.3 on 2020-11-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='pasw',
            new_name='pasw1',
        ),
    ]
